[package]
name = "lambda_create_user"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../core" }
tokio = { version = "1.38.0", features = ["full"] }
lambda_runtime = { version = "*"}
